### ISSUE TITLE
LGT8F328P nano style Holtec USB Serial not recognized?

### ISSUE THREAD

**Issue by maxint-rd** [dbuezas/arduino-web-oscilloscope#1]
Hello David, 
I've tried to use your fabulous looking web-oscilloscope, but it seems it can't connect to my LGT8F328P nano style board with onboard Holtec USB Serial adapter. I'm running Windows 7 32-bits (Yes, I know...) with an updated version of Google Chrome (Version 86.0.4240.75 (Official build) (32-bits). 

While the oscilloscope seems to run fine, it allows me to select a com-port. In the popup-window it shows all kind of ports, but it doesn't show the Holtec serial port of the LGT-board. That port is properly shown in the list of ports in the Arduino IDE and in the device-list of the Windows management console, but not in the web application.

When I insert a prolific serial adapter, that port is properly displayed, so I guess that could be a workaround, but I'd prefer to use the onboard USB connector. BTW. I also have some SOP20 boards laying around, but those don't have all analog pins available.
What can you suggest me to do?

**Comment by dbuezas** [comment]
Hi @maxint-rd ! Thanks for the kind words :)

SSOP20 boards should work fine, the oscilloscope can only read A0 as analog and A4,A5 ad digital.
You can get a second analog channel by using a second board but I didn't upload the instructions yet.


Regarding the holtek board in Windows, if it doesn't appear in the list, there's nothing I can do unfortunately, that's handled directly by the browser. I'll test it in a Windows machine this weekend anyway to be sure.

Have a nice week!

**Comment by maxint-rd** [comment]
Hi David,

Thank you for your swift response and for your clear explanation. Good to read that the SSOP20 board should work. 
It would be nice if you ever get the Nano-style board with the onboard Holtek chip working, but the SSOP20 with a separate Prolific board should be fine too.  (I haven tested it yet, but considered it fine enough to close this issue).

BTW. thank you very much for all your great work on the core files for this interesting board. I've happily used your work and  did some experimenting for my own projects. I'm still struggling a bit to get TIMER3 to do fast PWM, but that's a whole different topic...

**Comment by dbuezas** [comment]
:) thanks, happy to hear it it is useful for you.

Btw, I was also having problems with Timer3, and a contribuitor recently found out there's a couple of register which are wrongly defined. Check this issue: https://github.com/dbuezas/lgt8fx/issues/57#issue-comment-box

It will be fixed in the next release, but you can already get it to work by redefining the constants yourself (Use #undef)

**Comment by LaZsolt** [comment]
@maxint-rd :

Hi!
You need to dowload HOLTEK drivers for windows 7 or windows 8.
https://www.holtek.com/productdetail/-/vg/42B534-x
The driver .zip file can found under "Documents" tab.

They made this driver with an old signature. If you are unable to install driver, must set system date 2018 or earlyer for the setup time.

**Comment by maxint-rd** [comment]
> Btw, I was also having problems with Timer3, and a contribuitor recently found out there's a couple of register which are wrongly defined. Check this issue: [dbuezas/lgt8fx#57 (comment)](https://github.com/dbuezas/lgt8fx/issues/57#issue-comment-box)
> 
> It will be fixed in the next release, but you can already get it to work by redefining the constants yourself (Use #undef)

Oh, cool! Thanks you for that piece of info. When I was struggling to get it working I didn't even think that that could be the issue.

**Comment by maxint-rd** [comment]
> You need to dowload HOLTEK drivers for windows 7 or windows 8.
> https://www.holtek.com/productdetail/-/vg/42B534-x

Thank you @LaZsolt for the suggestion. I already have the driver working and the comm-port shows up in the Arduino IDE as well as in the Windows 7 device manager. It just doesn't show in the Crome box when connecting. Perhaps the Holtec driver is not compatible with this new Chrome feature.
But my Prolific board does show up, so I can use a SSOP20 pro-mini style board to test the oscilloscope.
