### ISSUE TITLE
Can't get a waveform or trigger

### ISSUE THREAD

**Issue by alunmorris** [dbuezas/arduino-web-oscilloscope#3]
Looks amazing but I can't get it to trigger or show a wave form. I have uploaded OK and pressed run. 
Serial status =Connected. Trigger = Searching. I have a TTL square wave as input. 
Channel = A0, trigger A0, Auto. Run button is green

I have tried a Chromebook and a Windows 10 PC.
The LGT8F328P is connected via a CH340 USB bridge.

**Comment by dbuezas** [comment]
Channel A0 is blue and you connected it to channel A0, right? Did you also connect the grounds of the board and your device under test?

**Comment by alunmorris** [comment]
> Channel A0 is blue and you connected it to channel A0, right? Did you also connect the grounds of the board and your device under test?
Yes.
> What time scale and volts per division do you have?
I tried various timescales down to 61us/div and input frequencies including a few 100Hz. 500mV/div for a 0-5V input signal.
I don't know what channel AS is. I tried clicking that as well.
I've just tried connecting A0 to TxD. Also A4. No go.
Could there be an issue with using a separate CH340 instead of an all-in-one MPU module?

**Comment by dbuezas** [comment]
> Could there be an issue with using a separate FTDI instead of an all-in-one MPU module?
it shouldn't. But if the RTS and DTS lines are not connected, you have to manually reset the board right after it connects. The browser and the MCU exchange some state synchronisation messages at start

**Comment by alunmorris** [comment]
My MPU module has no CTS. I noticed I had to reset the board just as I hit Upload.
I have now pulled CTS down on the FTDI. No help. I have tried resetting as I Connect, just before and just after I Connect. No help.

**Comment by dbuezas** [comment]
There is an issue in the arduino core repo for this board which may be relevant for you:
https://github.com/dbuezas/lgt8fx/issues/4

**Comment by DurandA** [comment]
I have the same issue. Sometimes it works and sometimes it doesn't.

The UART bridge of my board is a [HT42B534](https://www.holtek.com/documents/10179/116711/HT42B534-xv110.pdf) but the CTS/RTS pins are left unconnected.

![lgt328p](https://user-images.githubusercontent.com/3709037/108886859-c497d480-7609-11eb-957a-f6e0ed5263a1.png)

**Comment by alunmorris** [comment]
> There is an issue in the arduino core repo for this board which may be relevant for you:
> [dbuezas/lgt8fx#4](https://github.com/dbuezas/lgt8fx/issues/4)
I can program it with Arduino, setting the board as LGT8F328P-LQPF-32 MiniEVB. It has the SSOP-20 package but I can flash a LED.

**Comment by alunmorris** [comment]
I've ordered an couple of LGT8F328P nanos with USB. I've just got to try your amazing project.

**Comment by dbuezas** [comment]
> I have the same issue. Sometimes it works and sometimes it doesn't.
That's interesting... I developed in the same board and I had no issues. If anybody else has issues, please let me know.
