### ISSUE TITLE
Sinus Zero offset

### ISSUE THREAD

**Issue by Shumatic** [dbuezas/arduino-web-oscilloscope#7]
Thanks for sharing this tool.

When i meas. a sinus of 1V on A0, it cut off 1/3 of the curves buttom
If i then changes to 50mV i shows right.
if i increase to 100mV it shows right, but start cutting buttom again within 5 sec.
I have also tried with a capasitor in series and an completely seperate generator.

Squrewave with ref. to Zero shows right, though the V scale is wrong if you 
input 10Khz 4V - and choose 500mV/div and 101uS/div, it shows only 2.5V

I have a normal scope, it show everything right.

**Comment by dbuezas** [comment]
Hi! Yes the adc of the lgt328p has some limitations when used at high speeds. I should have made those more clear in the UI. 
Also you can't measure voltages below gnd (you can put a cap in series and add a 2.5 v bias between A0 and the cap. For that, you can use a voltage divider, just pick high values like 100k to avoid attenuating the signal
